# Generated by Django 5.2.4 on 2025-07-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_parent_category_alter_district_city_estate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='parent_category',
        ),
    ]
